const TOOL_NAME = 'gqlfake'
const GENERATE_DIRECTIVE_NAME = 'generate'
const GENERATE_DIRECTIVE_ARGUMENT_NAME = 'data'

export {
    TOOL_NAME,
    GENERATE_DIRECTIVE_NAME,
    GENERATE_DIRECTIVE_ARGUMENT_NAME
}
